project:
  type: website
  output-dir: docs
  
website:
  title: "Medienagentur Geschichte"
  cookie-consent: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Aktuelles.qmd
      - Fernsehen.qmd
      - Hoerfunk.qmd
      - Kontakt.qmd
    background: "light"
 
  sidebar:
    logo: "Images/FM3_3911.jpg"
    pinned: true
    align: center
    header: "Dr. Tillmann Bendikowski"
    footer: "Leiter der Medienagentur Geschichte und erster Ansprechpartner für alle Fragen."
    
  page-footer:
    left: "2022"
    right: 
      - href: Datenschutz.qmd
      - href: Impressum.qmd
    
format:
  html:
    theme: simplex
    css: styles.css
    toc: false
    title-block-banner: "Images/banner_books_wide.png"
    title-block-style: default
    title-block-categories: false
    title-block-banner-color: body
    
editor: visual

