project:
  type: website
  output-dir: docs
  
website:
  title: "Medienagentur Geschichte"
  image: Minard.png
  cookie-consent: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Aktuelles.qmd
      - Fernsehen.qmd
      - Hoerfunk.qmd
      - Kontakt.qmd
    background: "light"
  
  page-footer:
    left: "2022"
    right: 
      - href: Datenschutz.qmd
      - href: Impressum.qmd
    
format:
  html:
    theme: simplex
    css: styles.css
    toc: false
    title-block-banner: "Images/aviation.png"
    title-block-style: default
    title-block-categories: false
    title-block-banner-color: body
    
editor: visual

